<?php
/**
* Labels
*/
class Labels
{
	static $lang = array(
		'pt'=>array(
					'currency'				=> '€',
					'flash_add_store'		=> 'Adicionado com sucesso.',
					'flash_remove_store'	=> 'Removido com sucesso.',
					'flash_update_store'	=> 'Actualizado com sucesso.',
					'msg_login_failded'		=> 'Utilizador/palavra-passe inv&aacute;lidos.',
					'msg_logout'			=> 'Encerrado sessão.',
					'next'					=> 'Pr&oacute;ximo',
					'previous'				=> 'Anterior',
					'home'					=> 'In&iacute;cio',
					'search'				=> 'Pesquisa',
					'buy'					=> 'Comprar',
					'manufacture'			=> 'Fabricante',
					'similar'				=> 'Similar',
					'comments'				=> 'Coment&aacute;rio',
					'send_friend'			=> 'Enviar a um amigo',
					'your_name'				=> 'Seu nome',
					'your_email'			=> 'Seu e-mail',
					'your_address'			=> 'Seu endere&ccedil;o',
					'name_friend'			=> 'Nome de seu amigo',
					'email_friend'			=> 'Email de seu amigo',
					'message'				=> 'Mensagem',
					'send'					=> 'Enviar',
					'subject'				=> 'Assunto',
					'contact'				=> 'Contacto',
					'cart_label'			=> 'Carrinho de Compras',
					'items'					=> 'Item(ns)',
					'total'					=> 'Total',
					'select_attrib'			=> 'Por favor seleccione primeiro um tamanho',
					'restrict_area'			=> 'Area restrita. Por favor, faça login',
					'invalid'				=> 'Invalido',
					'required'				=> 'Requerido',
					),
		'en'=>array(
					'currency'				=> '€',
					'flash_add_store'		=> 'Added product in store.',
					'flash_remove_store'	=> 'Removed from store.',
					'flash_update_store'	=> 'Updated your store.',
					'msg_login_failded'		=> 'Username/password not found',
					'msg_logout'			=> 'Logout!',
					'next'					=> 'Next',
					'previous'				=> 'Previous',
					'home'					=> 'Home',
					'search'				=> 'Search',
					'buy'					=> 'Buy',
					'manufacture'			=> 'Manufacture',
					'similar'				=> 'Similar',
					'comments'				=> 'Comments',
					'send_friend'			=> 'Send a friend',
					'your_name'				=> 'Your name',
					'your_email'			=> 'Your e-mail',
					'your_address'			=> 'Your address',
					'name_friend'			=> 'Your friend name',
					'email_friend'			=> 'Your friend e-mail',
					'message'				=> 'Message',
					'send'					=> 'Send',
					'subject'				=> 'Subject',
					'contact'				=> 'Contact',
					'cart_label'			=> 'Shopping Cart',
					'items'					=> 'Item(ns)',
					'total'					=> 'Total',
					'select_attrib'			=> 'Please, select first a weight',
					'restrict_area'			=> 'Restric area. Please, Login first',
					'invalid'				=> 'Invalid',
					'required'				=> 'Required',
					),
		'es'=>array(
					'currency'				=> '€',
					'flash_add_store'		=> 'Adicionado com sucesso.',
					'flash_remove_store'	=> 'Removido com sucesso.',
					'flash_update_store'	=> 'Actualizado com sucesso.',
					'msg_login_failded'		=> 'Utilizador/palavra-passe não encontrados.',
					'msg_logout'			=> 'Encerrado sessão.',
					'next'					=> 'Próximo',
					'previous'				=> 'Anterior',
					'home'					=> 'Inicio',
					'search'				=> 'Pesquisa',
					'buy'					=> 'Comprar',
					'manufacture'			=> 'Fabricante',
					'similar'				=> 'Similar',
					'comments'				=> 'Comments',
					'send_friend'			=> 'Enviar a um amigo',
					'your_name'				=> 'Seu nome',
					'your_email'			=> 'Seu e-mail',
					'your_address'			=> 'Seu endereco',
					'name_friend'			=> 'Nome de seu amigo',
					'email_friend'			=> 'Email de seu amigo',
					'message'				=> 'Mensagem',
					'send'					=> 'Enviar',
					'subject'				=> 'Assunto',
					'contact'				=> 'Contacto',
					'cart_label'			=> 'Carrinho de compras',
					'items'					=> 'Item(ns)',
					'total'					=> 'Total',
					'select_attrib'			=> 'Por favor seleccione primeiro um tamanho',
					'restrict_area'			=> 'Restric area. Please, Login first',
					'invalid'				=> 'Invalido',
					'required'				=> 'Requerido',
					)
		);
		
		
	static function select($value)
	{
		return (in_array($value, array_keys(self::$lang))) ? self::$lang[$value] : self::$lang[Config::$languages[0]];
	}
}

?>